import random

name = input("What is your name? ")
print("Good Luck ! ", name)
words = ['rainbow', 'computer', 'science', 'programming', 'python', 'mathematics', 'player', 'condition',
         'reverse', 'water', 'board', 'geeks', 'alcohol', 'copy', 'paste', 'milk', 'empty', 'floor', 'come', 'hundred',
         'coding', 'getup', 'vegetables', 'spacebar', 'control', 'oldman', 'talking', 'eating', 'wnated', 'lie',
         'equal', 'separate', 'wordgame', 'monk', 'india', 'indian', 'america', 'american', 'put', 'hut', 'exam',
         'blue', 'green', 'laptop', 'lockdown', 'college', 'mistake', 'learn', 'friend', 'relative', 'spoon', 'school',
         'telegram', 'drahon', 'army', 'thermodynamics', 'mechanical', 'work', 'wrong', 'language', 'write', 'read',
         'help', 'running', 'brother', 'parents', 'hotter', 'sunlight', 'cement', 'record', 'operating', 'singing',
         'humming', 'swimming', 'complex', 'clean', 'hair', 'game', 'bell', 'temple', 'church', 'religion', 'contact',
         'message', 'coconut', 'ringing', 'vibrate', 'project', 'screte', 'palace', 'estivation', 'regnant', 'candy',
         'unknown', 'playground', 'pitch', 'mother', 'father', 'canyon', 'evidence', 'imposter', 'lift', 'function',
         'birthday', 'marraige', 'cake', 'snail', 'lighting', 'typing', 'river', 'strawberry', 'table', 'package',
         'startup', 'myrmidon', 'terpsichorean', 'oneiromancy', 'mate', 'siblings', 'old', 'gold', 'silver', 'paltinum',
         'oneiromancy', 'party', 'fry', 'compiler', 'processor', 'submit', 'oneiromancy', 'area', 'clinic', 'weight',
         'pass', 'result', 'universe', 'slim', 'diet', 'corona', 'immunity', 'village', 'town', 'mindset', 'attractive',
         'shoppingmall', 'theater', 'hsopital', 'curd', 'interview', 'bread', 'animal', 'feather', 'where', 'who',
         'what', 'cream', 'breakfast', 'butter', 'countdown', 'transparent', 'shoes', 'local', 'attitude', 'mission',
         'critical', 'overtime', 'remember', 'forget', 'database', 'qualification', 'multinational', 'shipment',
         'callcentre', 'knowledge', 'skills', 'labour', 'factory', 'impossible', 'fairytale', 'choclate', 'weak',
         'sunday', 'dozon', 'dumb', 'instrument', 'store', 'leave', 'tomorrowm', 'yesterday', 'white', 'balck',
         'rainbow', 'stereo', 'audio', 'audioplayer', 'quality', 'algorithm', 'motorcycle', 'indicator', 'forum',
         'multiplex', 'plantation', 'migrate', 'desert', 'solar', 'invertor', 'time', 'inversion', 'cinematography',
         'million', 'moonlight', 'grammar', 'gravity', 'mailbox', 'map', 'offline', 'micro', 'operation', 'labs',
         'development', 'date', 'bronze', 'oxygen', 'carbon', 'dioxide', 'helium', 'octacore', 'quadcore', 'tomato',
         'track', 'delivery', 'farmer', 'minister', 'orange', 'apple', 'banana', 'guava', 'tool', 'kit', 'repair',
         'triple', 'percentage', 'century', 'streak', 'mango', 'double', 'power', 'camp', 'fire', 'primary',
         'secondary', 'internet', 'stomach', 'physical', 'mental', 'heart', 'pair', 'parachute', 'believe', 'painful',
         'compose', 'studio', 'partner', 'crime', 'gateway', 'hexacore', 'management', 'chairman', 'president',
         'skating', 'shaking', 'melody', 'ocean', 'blood', 'antidust', 'lucky', 'businessman', 'international',
         'national', 'elections', 'ballotbox', 'integrated', 'alert', 'punch', 'popup', 'shirt', 'imigration', 'turbo',
         'military', 'attend', 'absent', 'clear', 'wireless', 'screenshot', 'newsreporter', 'multimedia', 'statement',
         'dairy', 'farm', 'prime', 'parliament', 'flag', 'gas', 'vaccine', 'booking', 'bank', 'deposit', 'credit',
         'mask', 'statement', 'phone', 'telephone', 'speed', 'petroleum', 'card', 'organnisation', 'voting', 'counters',
         'counting', 'stadium', 'commisoner', 'incharge', 'inside', 'outside', 'boundary', 'deputy', 'division', 'pool',
         'pole', 'polling', 'repolling', 'institution', 'statue', 'action', 'nine', 'twelve', 'swimmingpool',
         'publicity', 'municipality', 'information', 'isolation', 'litre', 'profit', 'collection', 'collector',
         'toothpaste', 'handwash', 'hearing', 'jeep', 'press', 'backside', 'caught', 'bowling', 'socail', 'chemistry',
         'subject', 'belief', 'cattle', 'thousand', 'sufficient', 'glasses', 'shampoo', 'soap', 'hosting', 'paltform',
         'metro', 'domain', 'free', 'service', 'cart', 'install', 'installment', 'journey', 'ox', 'cost', 'canvas',
         'advertisement', 'cyber', 'wheel', 'bullockcart', 'building', 'education', 'environment', 'notes',
         'individual', 'new', 'refresh', 'website', 'lightup', 'laugh', 'lighthouse', 'beach', 'continent', 'pacific',
         'noun', 'verb', 'nature', 'herbal', 'lifetime', 'understanding', 'sucess', 'successful']
word = random.choice(words)
print(word)
